name: 'data_pipeline'
profile: 'pipeline'

config-version: 2
version: '0.1'

model-paths:
  - "models"

target-path: "target"
log-path: "logs"
packages-install-path: "dbt_modules"

clean-targets:
  - "target"
  - "dbt_modules"

quoting:
  database: false
  schema: false
  identifier: false

models:
  materialized: table
