version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=clara
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=training_txn
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL"]
      interval: 60s
      timeout: 30s
      retries: 5

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.0
    environment:
      DBT_PROFILES_DIR: /dbt/profile
    volumes:
      - ./dbt:/dbt
    depends_on:
      - db